### ISSUE TITLE
Doesn't work behind an http_proxy

### ISSUE THREAD

**Issue by WaltHP** [Infinidat/infi.projector#4]
I'm trying to work on adding some features to the info.multipathtools project.
trying to build the project I get failures not being able to pull down packages.
I have my http_proxy and https_proxy environment variables set, but I can't get it to work at all.

I'm on ubuntu 16.04

`vagrant@ubuntubox:~/infi.multipathtools:(git::develop) $  projector devenv build
Executing /usr/bin/python -S bootstrap.py --index-url=https://pypi.python.org/simple
Command falied with -S, trying without
Executing /usr/bin/python bootstrap.py --index-url=https://pypi.python.org/simple
Traceback (most recent call last):
  File "/usr/local/bin/projector", line 11, in <module>
    load_entry_point('infi.projector==0.6.47', 'console_scripts', 'projector')()
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/scripts/__init__.py", line 10, in projector
    parse_commandline_arguments(argv)
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/commandline_parser/__init__.py", line 125, in parse_commandline_arguments
    if not any(selected_plugin.parse_commandline_arguments(arguments) for selected_plugin in selected_plugins):
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/commandline_parser/__init__.py", line 125, in <genexpr>
    if not any(selected_plugin.parse_commandline_arguments(arguments) for selected_plugin in selected_plugins):
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/plugins/__init__.py", line 27, in parse_commandline_arguments
    method()
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/plugins/builtins/devenv/__init__.py", line 187, in build
    self.bootstrap_if_necessary()
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/plugins/builtins/devenv/__init__.py", line 100, in bootstrap_if_necessary
    utils.execute_with_python(self._get_bootstrap_command())
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/helper/utils/__init__.py", line 93, in execute_with_python
    execute_assert_success(executable + args)
  File "/usr/local/lib/python2.7/dist-packages/infi/projector/helper/utils/__init__.py", line 63, in execute_assert_success
    raise PrettyExecutionError(result)
infi.projector.helper.utils.PrettyExecutionError: Execution of ['/usr/bin/python', 'bootstrap.py', '--index-url=https://pypi.python.org/simple'] failed!
result=1
stdout=
stderr=Downloading https://pypi.io/packages/source/s/setuptools/setuptools-28.0.0.zip
Extracting in /tmp/tmpZaKlkB
Now working in /tmp/tmpZaKlkB/setuptools-28.0.0
Building a Setuptools egg in /tmp/tmpNWBvAy
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/tmpNWBvAy/setuptools-28.0.0-py2.7.egg
/tmp/tmpNWBvAy/setuptools-28.0.0-py2.7.egg/pkg_resources/__init__.py:190: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Traceback (most recent call last):
  File "bootstrap.py", line 274, in <module>
    ws.require(requirement)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 970, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 856, in resolve
pkg_resources.DistributionNotFound: The 'zc.buildout==2.5.3' distribution was not found and is required by the application
`

**Comment by amito** [comment]
Hi, thanks for reporting on the issue.
Just a side note on multipathtools: please be advised that multipathtools is still not fully verified on Ubuntu 16.04 at the moment. We have also encountered some bugs in the Ubuntu multipath-tools package in the repo (See: [LP 1629644](https://bugs.launchpad.net/ubuntu/+source/multipath-tools/+bug/1629644) and [https://bugs.launchpad.net/ubuntu/+source/multipath-tools/+bug/1611360](1611360)). 
Are you working on a 32 or 64 bit machine?

**Comment by amito** [comment]
After creating a host-proxy setup I could not reproduce the issue. Can you maybe give more details about your setup?
